### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by timbur** [creationix/tedit#62]
Continued from https://github.com/jspm/jspm-cli/issues/849#issuecomment-112581257...

@creationix What do you think would be the ideal feature set for tedit?

**Comment by creationix** [comment]
I want tedit to be a bare core with extensions.  The core needs to have a git based filesystem because of the interesting properties this has for cache invalidation.

 - Full FS editing with codemirror / ace editing (I actually want to move to codemirror)
 - FS operations like rename, move, copy, delete, etc.  Perhaps with an explorer/finder style interface.
 - History view.  We have all this rich history metadata waiting to be used.  The fs view can have time-machine abilities, we can see diffs, see git logs per file or per folder, etc. (js-git alone can't do this yet)
 - Network interaction for downloading and publishing git code (https protocol, ssh protocol, tcp protocol, websocket protocol, github API protocol)  This can be part of the extension system since not all platforms can do all protocols without external assistance.
 - Merge / diff support (not implemented at all)
 - Submodule updater with semver support for checking semver ranges of remote tags and suggesting updates.

Some more extensions are things like runtimes and compilers.  I want to be able to spawn a local http server and write server-side projects in tedit (the chrome app can do this).  It would be really cool if we could hook in transpilers and vms and program other languages.  Maybe even include cloud support and platform serial APIs or browser plugins and program IoT devices like arduinos.

The goal is to provide a workspace for people to make things on devices that don't have traditional development environments (command-line + system access)

**Comment by creationix** [comment]
It might be possible to simulate an http server using service workers in the browser.  We can add raw TCP support by deploying a few websocket - tcp gateways on the net (or allowing people to deploy their own and specify it in some config).  Also we can create a new network using webrtc data channels that also has gateways to the real internet.  I'd love to create such a hybrid network.

**Comment by timbur** [comment]
I prefer codemirror as well.  :)  There are some really cool plugins for it (namely point-and-click diffing/merging), plus Chrome's dev tools uses it, so when the Chrome dev tools team makes the inspector itself [more easily extendable](https://stackoverflow.com/questions/29346370/is-there-a-way-to-watch-for-the-keyup-event-when-editing-a-resource-via-chromes#comment-47335585), I think it would be entirely feasible to incorporate `tedit` (or certain functionality, at least) into an extension that works directly with all of WebKit's/Chrome's existing dev tools.

Interesting ideas about the git history and simulated servers.  A hybrid webrtc network would be awesome as well.

Here's what I'm working on right now, two main things:

1.  The `web-tedit` package mainly exports a function that you pass a URL to, and it will create an iframe that contains the page, and the page should be designed to load a handful of `web-tedit` plugins for communication, hot reloading, etc.  It will automatically add decorators to React components (for example), that allow you to click on components within the page to edit their code, move them around, etc.  Right now, doing this is as easy as using the following logic for the main script, but I would like to somehow turn it into either a Babel plugin or a single simple `script` to include:
    ```js
<script>
(function () {
  var tedit = window.frameElement && window.frameElement.tedit;

  if (tedit) {
    // configure this window's System to use `web-tedit`
    tedit.init(System);
    System.import('src/main');
  } else {
    // load `web-tedit` as a wrapper around the current page
    System.import('web-tedit').then(function (tedit) {
      tedit(window.location.pathname);
    });
  }
})();
</script>
    ```

2.  Similar to what you mentioned about spinning up servers, it would be fantastic to automatically do that based on the requirements of the client code.  These days, for modern web apps, servers are rarely used as more than REST APIs and maybe to provide some media.  So I think it would be relatively easy to create plugins that would, for example, when using something like [GraphQL](https://facebook.github.io/react/blog/2015/05/01/graphql-introduction.html), automatically generate modules/packages designed to be used as a Node.js server and custom tailored for the data requirements of the client.  A week and a half ago, I released roughly [16 REST API decorators](https://github.com/loggur/baucis-decorators) which should make creating said plugin fairly trivial.

I'm hoping that after I resolve these issues with SystemJS, I'll be able to get all of this implemented quickly.
